networks:
  simple_auth_net:
    driver: bridge

services:

  ## Mognodb
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - simple_auth_net

  ## Mongo Express Client
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - simple_auth_net

  ## Apache UI
  apache-ui:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: 'simple-auth-ui'
    ports:
      - '8100:80'
    working_dir: /var/www/html
    volumes:
      - ./ui:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
    networks:
      - simple_auth_net

  ## NestJS API
  api:
    image: simple_auth_api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://root:example@mongo:27017/
    container_name: 'simple-auth-api'
    ports:
      - '4000:3000'
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules
    external_links:
      - mongo
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - simple_auth_net